In [1]:
import plotly.express as px
import pandas as pd

In [3]:
df = pd.read_csv('data_collection.csv')
df.tail()

,timestamp,ram,database,embedding,llm,prompt,response_time_sec,response_length,prompt_length
179,2025-04-02T21:58:31.566228,24.0,weaviate,minilm,llama3.2:latest,What does the $nin operator mean in a Mongo qu...,2.684064,435,717
180,2025-04-02T22:00:07.096322,24.0,redis,mxbai,mistral:latest,What is the difference between a list where me...,7.123628,528,1898
181,2025-04-02T22:00:13.805473,24.0,chroma,mxbai,mistral:latest,What is the difference between a list where me...,6.708216,633,1252
182,2025-04-02T22:00:22.572612,24.0,weaviate,mxbai,mistral:latest,What is the difference between a list where me...,8.524959,951,1252
183,2025-04-02T22:00:34.019145,24.0,redis,mxbai,llama3.2:latest,What is the difference between a list where me...,11.442495,1015,1898

In [27]:
fig = px.scatter(df, x='prompt_length', y='response_time_sec', color='database',
                 hover_data=df.columns)
fig.update_layout(xaxis_title='Prompt Length (characters)',
                  yaxis_title='Response Time (seconds)')
fig.show()

In [40]:
fig = px.histogram(df, x='response_time_sec', nbins=30)
fig.update_layout(xaxis_title='Response Time (seconds)',
                  yaxis_title='Count')
fig.show()

In [32]:
fig = px.violin(df, x='llm', y='response_time_sec', color='embedding',
                 hover_data=df.columns)
fig.update_layout(xaxis_title='LLM',
                  yaxis_title='Response Time (seconds)',)
fig.show()

In [25]:
fig = px.scatter(df, x='response_length', y='response_time_sec', color='prompt',
                 hover_data=df.columns)
fig.update_layout(showlegend=False, 
                  xaxis_title='Response Length (characters)',
                  yaxis_title='Response Time (seconds)')
fig.show()

In [18]:
df[['response_time_sec', 'response_length', 'prompt_length']].corr()

                   response_time_sec  response_length  prompt_length
response_time_sec           1.000000         0.728362       0.580737
response_length             0.728362         1.000000       0.324596
prompt_length               0.580737         0.324596       1.000000